### PR TITLE
Gateway Configuration with Timeouts

### LINKED ISSUE #95: Allow configurable HTTP timeout in Gateway
To resolve #94 or provide temporary work-around.

## Expected Behavior

The API Gateway has hard-coded 8-second timeout, this should be configurable. Most people will want this to be shorter - some longer.

## Current Behavior

8-seconds is the max duration

## Possible Solution

Introduce environmental configuration to match that of the watchdog's configuration options.

https://github.com/alexellis/faas/blob/master/watchdog/readconfig.go

## Steps to Reproduce (for bugs)

See #94 or set `fprocess` to `sleep 10`.

cc/ @stealthybox

### PR DESCRIPTION
**Pull request by stealthybox**
New feature for Gateway Configuration Options

## Description

- Adds GatewayConfig
- Env configurable `read_timeout` & `write_timeout` /w test copied over from watchdog.
- Moves httpPort definition to the config default declaration.
- Modifies Dockerfiles to add new files and test code.
- Adds runtime logging for options.

## Motivation and Context
Resolves #95 and #94 

## How Has This Been Tested?
Unit test and config were included in the `main` package instead of the `tests` folder because of access to unexported struct members.
The additional test gates the build.
This follows the same format as the watchdog.

I tested e2e functionality by setting the `read_timeout` and `write_timeout` ENV vars on the gateway container, checking the new log output, and following the steps in #94.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: gateway/readconfig.go [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+
+	cfg.readTimeout = time.Duration(readTimeout) * time.Second
+	cfg.writeTimeout = time.Duration(writeTimeout) * time.Second
+
+	return cfg
+}
+
+// GatewayConfig for the process.
+type GatewayConfig struct {
+	httpPort     int
```
Comment (alexellis) [inline gateway/readconfig.go]: Let's not make the httpPort configurable - there are assumptions that the port is fixed.

File: gateway/server.go [hunk 2]
```diff
@@ -20,6 +19,14 @@ func main() {
 	logger := logrus.Logger{}
 	logrus.SetFormatter(&logrus.TextFormatter{})
 
+	osEnv := OsEnv{}
+	readConfig := ReadConfig{}
+	config := readConfig.Read(osEnv)
+
+	log.Printf("HTTP Port: %d", config.httpPort)
```
Comment (alexellis) [inline gateway/server.go]: Please remove the HTTP port config.

File: gateway/readconfig.go [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+// Read fetches config from environmental variables.
+func (ReadConfig) Read(hasEnv HasEnv) GatewayConfig {
+	cfg := GatewayConfig{
+		httpPort: 8080,
+	}
+
+	readTimeout := parseIntValue(hasEnv.Getenv("read_timeout"))
+	writeTimeout := parseIntValue(hasEnv.Getenv("write_timeout"))
+
+	if readTimeout == 0 {
```
Comment (alexellis) [inline gateway/readconfig.go]: Let's modify parseIntValue to take a default override value as a parameter - therefore if parsing fails we get the default value instead. That will make the code a bit more concise too.

File: gateway/readconfig.go (hunk 1 above)
Comment (stealthybox) [inline gateway/readconfig.go]: This was still hard-coded -- just moved it into the config struct.
I have removed it since it was out of scope.

File: gateway/readconfig.go (hunk 3 above)
Comment (stealthybox) [inline gateway/readconfig.go]: Awesome suggestion -- implemented it and it's much cleaner.

**Comment by stealthybox** [comment]
Thanks for the review -- changes are pushed.

File: gateway/config_test.go [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+
+func (e EnvBucket) Getenv(key string) string {
+	return e.Items[key]
+}
+
+func (e EnvBucket) Setenv(key string, value string) {
+	e.Items[key] = value
+}
+
+func TestRead_ReadAndWriteTimeoutConfig(t *testing.T) {
```
Comment (alexellis) [inline gateway/config_test.go]: We also need a unit test to show the default behaviour of 8 seconds for both variables if they are not set.

File: gateway/Dockerfile.build [hunk 5]
```diff
@@ -10,13 +10,16 @@ FROM golang:1.7.5
...
-COPY requests   requests
-COPY tests      tests
-COPY server.go  .
+COPY handlers       handlers
+COPY metrics        metrics
+COPY requests       requests
+COPY tests          tests
+COPY server.go      .
+COPY readconfig.go  .
+COPY config_test.go .
```
Comment (alexellis) [inline gateway/Dockerfile.build]: Would it be tricky to put config_test.go into the tests folder?

File: gateway/config_test.go (hunk 4 above)
Comment (stealthybox) [inline gateway/config_test.go]: We should add one for the watchdog as well ( unless I missed it )

File: gateway/Dockerfile.build (hunk 5 above)
Comment (stealthybox) [inline gateway/Dockerfile.build]: I started with it in the tests folder when I had this realization ^

File: gateway/config_test.go (hunk 4 above)
Comment (alexellis) [inline gateway/config_test.go]: "Go" for it.

Comment (stealthybox) [inline gateway/config_test.go]: Watchdog has a test for empty config -- I missed it the first time.
Added to gateway /w 8 sec.

File: gateway/Dockerfile.build (hunk 5 above)
Comment (alexellis) [inline gateway/Dockerfile.build]: Let's export them then.

Comment (stealthybox) [inline gateway/Dockerfile.build]: @alexellis I pushed a commit that exports the fields and moves `config_test` to the *tests* package.

**Comment by alexellis** [comment]
@stealthybox thanks for the updates. I've got this on my list for testing / merging.

**Comment by stealthybox** [comment]
@alexellis appreciate the critique -- looking forward to it :whale:

**Comment by stealthybox** [comment]
🎉
